# Generated by Django 5.2.9 on 2025-12-03 08:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('single', 'Single')], max_length=10)),
                ('release_date', models.DateField()),
                ('cover_art', models.ImageField(upload_to='albums/')),
                ('description', ckeditor.fields.RichTextField()),
                ('spotify_url', models.URLField(blank=True)),
                ('apple_music_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('soundcloud_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('track_number', models.IntegerField()),
                ('duration', models.CharField(help_text='Format: MM:SS', max_length=10)),
                ('lyrics', ckeditor.fields.RichTextField(blank=True)),
                ('story_behind', ckeditor.fields.RichTextField(blank=True, help_text='Story behind the song')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album')),
            ],
            options={
                'ordering': ['album', 'track_number'],
            },
        ),
    ]
