# Generated by Django 5.2.9 on 2025-12-03 07:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('music', 'Music Updates'), ('faith', 'Faith & Reflection'), ('outreach', 'Outreach & Ministry'), ('announcement', 'Announcements'), ('personal', 'Personal')], max_length=20)),
                ('featured_image', models.ImageField(upload_to='blog/')),
                ('excerpt', models.TextField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(default='MW Music', max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
